/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOwnable } from "./IOwnable";
export type { ITokenReputation } from "./ITokenReputation";
export type { ITokenReputationFactory } from "./ITokenReputationFactory";
