import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AppLayout } from "@/sections/layout/AppLayout";
import { cn } from "@/utils/ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "w-screen min-h-screen")}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
