/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ProtocolConfigurationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_LEGACY_FEE_PERCENTAGE"
      | "ADMIN_RETAINED_TOKENS_PERCENTAGE"
      | "ADMIN_REVOKE_FEE_PERCENTAGE"
      | "GOVERNANCE_PERCENTAGE_TO_TOKENS_PERCENTAGE"
      | "INITIAL_CHILD_SUPPLY"
      | "INITIAL_SUPPLY"
      | "MAX_ADMIN_LEGACY_FEE_PERCENTAGE"
      | "MAX_ADMIN_RETAINED_TOKENS_PERCENTAGE"
      | "MAX_ADMIN_REVOKE_FEE_PERCENTAGE"
      | "MAX_INITIAL_SUPPLY"
      | "MAX_NETWORK_PARTICIPATION_PERCENTAGE"
      | "MAX_SUPPLY"
      | "NETWORK_PARTICIPATION_PERCENTAGE"
      | "NETWORK_TO_CHILD_ALLOCATION_PERCENTAGE"
      | "SPONSOR_TOKEN_REQUIREMENT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_LEGACY_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ADMIN_RETAINED_TOKENS_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ADMIN_REVOKE_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNANCE_PERCENTAGE_TO_TOKENS_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_CHILD_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ADMIN_LEGACY_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ADMIN_RETAINED_TOKENS_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ADMIN_REVOKE_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_INITIAL_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_NETWORK_PARTICIPATION_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NETWORK_PARTICIPATION_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NETWORK_TO_CHILD_ALLOCATION_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SPONSOR_TOKEN_REQUIREMENT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ADMIN_LEGACY_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ADMIN_RETAINED_TOKENS_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ADMIN_REVOKE_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNANCE_PERCENTAGE_TO_TOKENS_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_CHILD_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ADMIN_LEGACY_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ADMIN_RETAINED_TOKENS_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ADMIN_REVOKE_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_INITIAL_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_NETWORK_PARTICIPATION_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SUPPLY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "NETWORK_PARTICIPATION_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NETWORK_TO_CHILD_ALLOCATION_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SPONSOR_TOKEN_REQUIREMENT",
    data: BytesLike
  ): Result;
}

export interface ProtocolConfiguration extends BaseContract {
  connect(runner?: ContractRunner | null): ProtocolConfiguration;
  waitForDeployment(): Promise<this>;

  interface: ProtocolConfigurationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_LEGACY_FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  ADMIN_RETAINED_TOKENS_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  ADMIN_REVOKE_FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  GOVERNANCE_PERCENTAGE_TO_TOKENS_PERCENTAGE: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  INITIAL_CHILD_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  INITIAL_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  MAX_ADMIN_LEGACY_FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  MAX_ADMIN_RETAINED_TOKENS_PERCENTAGE: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  MAX_ADMIN_REVOKE_FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  MAX_INITIAL_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  MAX_NETWORK_PARTICIPATION_PERCENTAGE: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  MAX_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  NETWORK_PARTICIPATION_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  NETWORK_TO_CHILD_ALLOCATION_PERCENTAGE: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  SPONSOR_TOKEN_REQUIREMENT: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_LEGACY_FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ADMIN_RETAINED_TOKENS_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ADMIN_REVOKE_FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GOVERNANCE_PERCENTAGE_TO_TOKENS_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_CHILD_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_ADMIN_LEGACY_FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_ADMIN_RETAINED_TOKENS_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_ADMIN_REVOKE_FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_INITIAL_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_NETWORK_PARTICIPATION_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NETWORK_PARTICIPATION_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NETWORK_TO_CHILD_ALLOCATION_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SPONSOR_TOKEN_REQUIREMENT"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
